// Session persistence: one JSON file per session under <data>/sessions/,
// holding meta, full message transcript (never rewritten — the visible
// transcript is append-only even though model context may compact) and the
// telemetry ledger. Files are written atomically (tmp + rename).
use crate::types_rs::{CompactionRecord, MessageRecord, RequestStat, SessionBinding, SessionMeta, WriteLog};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionFile {
    pub meta: SessionMeta,
    #[serde(default)]
    pub messages: Vec<MessageRecord>,
    #[serde(default)]
    pub telemetry: Vec<RequestStat>,
    /// Boundary compaction (model-context only; transcript stays intact).
    #[serde(default)]
    pub compaction: Option<CompactionRecord>,
    /// Successful workspace writes with before/after snapshots (review panel).
    #[serde(default)]
    pub writes: Vec<WriteLog>,
}

pub struct SessionStore {
    dir: PathBuf,
}

impl SessionStore {
    pub fn new(data_dir: &Path) -> Self {
        let dir = data_dir.join("sessions");
        let _ = fs::create_dir_all(&dir);
        Self { dir }
    }

    fn path_for(&self, id: &str) -> PathBuf {
        // ids are generated by us (uuid v4) — sanitize anyway
        let safe: String = id.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '-').collect();
        self.dir.join(format!("{safe}.json"))
    }

    pub fn list(&self) -> Vec<SessionMeta> {
        let mut metas = Vec::new();
        if let Ok(entries) = fs::read_dir(&self.dir) {
            for e in entries.flatten() {
                let p = e.path();
                if p.extension().and_then(|x| x.to_str()) == Some("json") {
                    if let Ok(raw) = fs::read_to_string(&p) {
                        if let Ok(sf) = serde_json::from_str::<SessionFile>(&raw) {
                            metas.push(sf.meta);
                        }
                    }
                }
            }
        }
        metas.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
        metas
    }

    pub fn load(&self, id: &str) -> Result<SessionFile, String> {
        let p = self.path_for(id);
        let raw = fs::read_to_string(&p).map_err(|e| format!("会话不存在或不可读: {e}"))?;
        serde_json::from_str(&raw).map_err(|e| format!("会话文件损坏: {e}"))
    }

    pub fn save(&self, sf: &SessionFile) -> Result<(), String> {
        let p = self.path_for(&sf.meta.id);
        let tmp = self.dir.join(format!(".{}.tmp", sf.meta.id));
        let body = serde_json::to_string_pretty(sf).map_err(|e| e.to_string())?;
        fs::write(&tmp, body).map_err(|e| format!("写入失败: {e}"))?;
        fs::rename(&tmp, &p).map_err(|e| format!("提交失败: {e}"))
    }

    pub fn create(&self, kind: &str, bindings: Vec<SessionBinding>, title: &str) -> Result<SessionFile, String> {
        let now = now_ms();
        let meta = SessionMeta {
            id: uuid::Uuid::new_v4().to_string(),
            title: if title.trim().is_empty() { default_title(kind) } else { title.trim().to_string() },
            kind: kind.to_string(),
            created_at: now,
            updated_at: now,
            bindings,
            workspace: None,
            pinned: false,
            archived: false,
            wt: None,
            wf_gate: None,
            goal: None,
            goal_rounds: Vec::new(),
        };
        let sf = SessionFile {
            meta,
            messages: Vec::new(),
            telemetry: Vec::new(),
            compaction: None,
            writes: Vec::new(),
        };
        self.save(&sf)?;
        Ok(sf)
    }

    pub fn delete(&self, id: &str) -> Result<(), String> {
        let p = self.path_for(id);
        match fs::remove_file(&p) {
            Ok(()) => {}
            // already gone — still clean up any attachments below
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(format!("删除失败: {e}")),
        }
        // attachment images are app-managed (under the store's own dir) and
        // referenced only by the deleted session — remove them with it
        let _ = fs::remove_dir_all(self.dir.join("attachments").join(sanitize_id(id)));
        Ok(())
    }

    pub fn rename(&self, id: &str, title: &str) -> Result<SessionMeta, String> {
        let mut sf = self.load(id)?;
        sf.meta.title = title.trim().to_string();
        sf.meta.updated_at = now_ms();
        self.save(&sf)?;
        Ok(sf.meta)
    }

    pub fn set_bindings(&self, id: &str, bindings: Vec<SessionBinding>) -> Result<SessionMeta, String> {
        let mut sf = self.load(id)?;
        sf.meta.bindings = bindings;
        sf.meta.updated_at = now_ms();
        self.save(&sf)?;
        Ok(sf.meta)
    }

    pub fn set_workspace(&self, id: &str, workspace: Option<String>) -> Result<SessionMeta, String> {
        let mut sf = self.load(id)?;
        sf.meta.workspace = workspace.map(|w| w.trim().to_string()).filter(|w| !w.is_empty());
        sf.meta.updated_at = now_ms();
        self.save(&sf)?;
        Ok(sf.meta)
    }

    pub fn set_pinned(&self, id: &str, pinned: bool) -> Result<SessionMeta, String> {
        let mut sf = self.load(id)?;
        sf.meta.pinned = pinned;
        self.save(&sf)?;
        Ok(sf.meta)
    }

    pub fn set_archived(&self, id: &str, archived: bool) -> Result<SessionMeta, String> {
        let mut sf = self.load(id)?;
        sf.meta.archived = archived;
        self.save(&sf)?;
        Ok(sf.meta)
    }

    /// Attach/clear the session's git-worktree isolation state (worktree.rs).
    pub fn set_wt(&self, id: &str, wt: Option<crate::types_rs::WtState>) -> Result<SessionMeta, String> {
        let mut sf = self.load(id)?;
        sf.meta.wt = wt;
        sf.meta.updated_at = now_ms();
        self.save(&sf)?;
        Ok(sf.meta)
    }

    /// Fork a session at a message boundary: everything at or before
    /// `from_ts` (the clicked user message included) is copied into a fresh
    /// session with a new prefix identity; the original is untouched.
    pub fn branch(&self, id: &str, from_ts: u64) -> Result<SessionFile, String> {
        let sf = self.load(id)?;
        let mut meta = sf.meta.clone();
        meta.id = uuid::Uuid::new_v4().to_string();
        meta.title = format!("↳ {}", sf.meta.title);
        meta.created_at = now_ms();
        meta.updated_at = now_ms();
        meta.pinned = false;
        meta.archived = false;
        let out = SessionFile {
            meta,
            messages: sf.messages.iter().filter(|m| m.ts <= from_ts).cloned().collect(),
            // telemetry rows belong to the byte history; keep pre-branch rows
            telemetry: sf.telemetry.iter().filter(|r| r.ts < from_ts).cloned().collect(),
            compaction: sf.compaction.clone().filter(|c| c.upto_ts < from_ts),
            writes: sf.writes.iter().filter(|w| w.ts <= from_ts).cloned().collect(),
        };
        if out.messages.is_empty() {
            return Err("分支点之前没有消息".into());
        }
        self.save(&out)?;
        // the branched records may reference attachment images that live in
        // the ORIGINAL session's dir — copy them so the fork is self-contained
        let src = self.dir.join("attachments").join(sanitize_id(id));
        if src.is_dir() {
            let dst = self.dir.join("attachments").join(sanitize_id(&out.meta.id));
            let _ = fs::create_dir_all(&dst);
            for e in fs::read_dir(&src).into_iter().flatten().flatten() {
                if e.path().is_file() {
                    if let Some(name) = e.file_name().to_str() {
                        let _ = fs::copy(e.path(), dst.join(name));
                    }
                }
            }
        }
        Ok(out)
    }
}

pub fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Sanitize a session id for filesystem use (ids are our uuids anyway).
fn sanitize_id(id: &str) -> String {
    id.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '-').collect()
}

/// Sanitize an attachment filename (generated by us: `<ts>_<i>.<ext>`).
fn sanitize_filename(name: &str) -> String {
    name.chars()
        .filter(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
        .collect()
}

// ---- session image attachments ----
//
// Images live under <data>/sessions/attachments/<session_id>/, are written
// exactly once and never mutated afterwards — the byte-stability that
// model-context rebuilds (and therefore prefix-cache hits) depend on.

/// Attachment directory for one session (data_dir form for callers that
/// only hold the data root, e.g. agent tools / transcript assembly).
pub fn attachments_dir(data_dir: &std::path::Path, session_id: &str) -> std::path::PathBuf {
    data_dir.join("sessions").join("attachments").join(sanitize_id(session_id))
}

/// Persist images (mime + base64 payload) as attachment files; returns the
/// relative filenames in order. Filenames embed the write timestamp.
pub fn save_attachments(
    data_dir: &std::path::Path,
    session_id: &str,
    images: &[crate::prefix::ChatImage],
) -> Result<Vec<String>, String> {
    use base64::Engine as _;
    if images.is_empty() {
        return Ok(Vec::new());
    }
    let dir = attachments_dir(data_dir, session_id);
    fs::create_dir_all(&dir).map_err(|e| format!("创建附件目录失败: {e}"))?;
    let ts = now_ms();
    let mut names = Vec::new();
    for (i, img) in images.iter().enumerate() {
        let ext = match img.mime.as_str() {
            "image/jpeg" => "jpg",
            "image/webp" => "webp",
            "image/gif" => "gif",
            _ => "png",
        };
        let name = format!("{ts}_{i}.{ext}");
        let bytes = base64::engine::general_purpose::STANDARD
            .decode(img.b64.trim())
            .map_err(|e| format!("图片 base64 解码失败: {e}"))?;
        if bytes.is_empty() {
            return Err("图片内容为空".into());
        }
        fs::write(dir.join(&name), &bytes).map_err(|e| format!("写入附件失败: {e}"))?;
        names.push(name);
    }
    Ok(names)
}

/// Load attachment files back into wire-ready images (missing files are
/// skipped — a pruned attachment degrades to a text-only turn rather than
/// failing the whole rebuild).
pub fn load_attachments(
    data_dir: &std::path::Path,
    session_id: &str,
    files: &[String],
) -> Vec<crate::prefix::ChatImage> {
    use base64::Engine as _;
    let dir = attachments_dir(data_dir, session_id);
    let mut out = Vec::new();
    for f in files {
        let safe = sanitize_filename(f);
        if safe.is_empty() {
            continue;
        }
        let Ok(bytes) = fs::read(dir.join(&safe)) else {
            continue;
        };
        let mime = mime_of_ext(safe.rsplit('.').next().unwrap_or(""));
        out.push(crate::prefix::ChatImage {
            mime: mime.to_string(),
            b64: base64::engine::general_purpose::STANDARD.encode(&bytes),
        });
    }
    out
}

/// Data URI for one attachment — the frontend bubble renderer's source.
pub fn attachment_data_uri(
    data_dir: &std::path::Path,
    session_id: &str,
    filename: &str,
) -> Result<String, String> {
    use base64::Engine as _;
    let safe = sanitize_filename(filename);
    if safe.is_empty() {
        return Err("非法附件名".into());
    }
    let bytes = fs::read(attachments_dir(data_dir, session_id).join(&safe))
        .map_err(|e| format!("附件不存在: {e}"))?;
    let mime = mime_of_ext(safe.rsplit('.').next().unwrap_or(""));
    Ok(format!(
        "data:{mime};base64,{}",
        base64::engine::general_purpose::STANDARD.encode(&bytes)
    ))
}

fn mime_of_ext(ext: &str) -> &'static str {
    match ext {
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "gif" => "image/gif",
        _ => "image/png",
    }
}

fn default_title(kind: &str) -> String {
    match kind {
        "arena" => "竞技场".to_string(),
        _ => "新会话".to_string(),
    }
}

pub fn export_markdown(sf: &SessionFile) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", sf.meta.title));
    out.push_str(&format!(
        "> 导出于 {} · {} 条消息 · {} 条请求记录\n\n",
        chrono::Local::now().format("%Y-%m-%d %H:%M:%S"),
        sf.messages.len(),
        sf.telemetry.len()
    ));
    let mut last_user = String::new();
    for m in &sf.messages {
        match m.role.as_str() {
            "user" => {
                last_user = m.content.clone();
                out.push_str(&format!("## 🧑 用户\n\n{}\n\n", m.content));
            }
            "assistant" => {
                let lane = if sf.meta.kind == "arena" { format!("（泳道 {}）", m.lane + 1) } else { String::new() };
                out.push_str(&format!("## 🤖 助手{lane}\n\n"));
                if !last_user.is_empty() && sf.meta.kind == "arena" {
                    out.push_str(&format!("> Q: {}\n\n", last_user.replace('\n', "\n> ")));
                }
                out.push_str(&m.content);
                out.push_str("\n\n");
                if let Some(u) = &m.usage {
                    out.push_str(&format!(
                        "<sub>in {} · out {} · cached {}</sub>\n\n",
                        u.input.unwrap_or(0),
                        u.output.unwrap_or(0),
                        u.cached.unwrap_or(0),
                    ));
                }
            }
            _ => {}
        }
    }
    if !sf.telemetry.is_empty() {
        out.push_str("---\n\n## 📈 请求账本\n\n| # | 模型 | 输入 | 缓存命中 | 输出 |\n|---|------|------|----------|------|\n");
        for r in &sf.telemetry {
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                r.seq,
                r.model,
                r.input_tokens.unwrap_or(0),
                r.cached_tokens.unwrap_or(0),
                r.output_tokens.unwrap_or(0)
            ));
        }
    }
    out
}
